"""Public API for the pure poker-domain foundation."""

from .errors import (
    DuplicateCardError,
    HandAlreadyActiveError,
    InsufficientPlayersError,
    InvalidBlindsError,
    InvalidCardCollectionError,
    InvalidContenderError,
    InvalidContenderIdError,
    InvalidDealerError,
    InvalidDeckError,
    InvalidHandIdError,
    InvalidSeatingError,
    InvalidShowdownError,
    PokerDomainError,
)
from .evaluator import (
    EvaluatedContender,
    HandCategory,
    HandRank,
    ShowdownContender,
    ShowdownResult,
    evaluate_best,
    evaluate_five,
    evaluate_showdown,
)
from .model import (
    MAX_SEAT,
    MIN_SEAT,
    ActiveHand,
    Card,
    HandId,
    HandPhase,
    HandPlayer,
    PlayerId,
    Rank,
    SeatedPlayer,
    Suit,
    TableState,
    standard_deck,
)
from .transition import start_hand

__all__ = [
    "MAX_SEAT",
    "MIN_SEAT",
    "ActiveHand",
    "Card",
    "DuplicateCardError",
    "EvaluatedContender",
    "HandAlreadyActiveError",
    "HandId",
    "HandPhase",
    "HandPlayer",
    "HandCategory",
    "HandRank",
    "InsufficientPlayersError",
    "InvalidBlindsError",
    "InvalidCardCollectionError",
    "InvalidContenderError",
    "InvalidContenderIdError",
    "InvalidDealerError",
    "InvalidDeckError",
    "InvalidHandIdError",
    "InvalidSeatingError",
    "InvalidShowdownError",
    "PlayerId",
    "PokerDomainError",
    "Rank",
    "SeatedPlayer",
    "Suit",
    "ShowdownContender",
    "ShowdownResult",
    "TableState",
    "standard_deck",
    "evaluate_best",
    "evaluate_five",
    "evaluate_showdown",
    "start_hand",
]
